global using Basket;
global using Carter;
global using Catalog;
global using FluentValidation;
global using Ordering;
global using Serilog;
global using Shared.Behaviours;
global using Shared.Exceptions.Handler;
global using Shared.Extension;
