services:

  eshopdb:
    image: postgres
    restart: always

  distributedCache:
    image: redis

  seq:
    image: datalust/seq:latest
  messagebus:
    image: rabbitmq:management
  identity:
    image: quay.io/keycloak/keycloak:24.0.3
    # set shared memory limit when using docker compose
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile

volumes:
   postgres_eshopdb:

